/*
 * Host-side test for the reader page's decode/reassemble/broadcast logic
 * (spec #115, sub-issue #119). No camera, no browser, no live relay --
 * exactly the "deterministic reassembly/decode/id-recompute/broadcast-
 * payload construction" the ticket calls for (getUserMedia + a real relay
 * are verified by construction + review, per iOS getUserMedia being #106,
 * non-gating).
 *
 * The keystone fixture (fixtures/multiframe_fixture.json) is GENERATED by
 * tools/pipeline_test/gen_reader_fixture.c from a real build_event() call
 * (privkey=3 KAT, StarCapture vector A, tag "sm64", name "TEST", url-base
 * SM64NOSTR.PAGES.DEV -- the same fixture main.c's own
 * test_build_event_end_to_end() independently pins kBuildEventExpectedIdA/
 * kBuildEventExpectedSig against) -- its "frames" array is the cabinet's
 * REAL emitted QR content (structurally decoded off the real QR bitmaps via
 * qr_host_decode_alphanumeric, never hand-derived), so this test exercises
 * the reader's logic against the actual cabinet-side output, not a
 * synthetic stand-in.
 *
 * Run: cd reader && npm install && npm test
 * (npm install is required once, for the two independent-oracle
 * cross-checks below -- @noble/curves/nostr-tools, mirroring
 * tools/reference_event_id.js's own "not vendored, install before running"
 * convention.)
 */
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

import {
  base32Decode,
  parseFragmentHeader,
  stripUrl,
  reassembleFrames,
  unpackPayload,
  buildCanonicalEventFields,
  buildContentJson,
  serializeForId,
  computeEventId,
  decodeToBroadcastEvent,
  buildRelayMessage,
} from '../reader.js';
import { bytesToHex, hexToBytes } from '../sha256.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const fixture = JSON.parse(readFileSync(path.join(__dirname, 'fixtures', 'multiframe_fixture.json'), 'utf8'));

// --- base32: RFC 4648 section 6 known-answer vectors (no padding), the
// same "ASCII" test vector family the RFC's own base32 test suite uses --
// mirrors src/pipeline's own base32 KAT convention (base32.h's own header
// comment), ported here as an independent sanity check of base32Decode
// before trusting it against the fixture. ---
test('base32Decode: RFC 4648 known-answer vectors', () => {
  const vectors = [
    ['', ''],
    ['MY', 'f'],
    ['MZXQ', 'fo'],
    ['MZXW6', 'foo'],
    ['MZXW6YQ', 'foob'],
    ['MZXW6YTB', 'fooba'],
    ['MZXW6YTBOI', 'foobar'],
  ];
  for (const [encoded, expectedAscii] of vectors) {
    const decoded = base32Decode(encoded);
    assert.equal(Buffer.from(decoded).toString('ascii'), expectedAscii, `base32Decode(${JSON.stringify(encoded)})`);
  }
});

test('base32Decode: rejects a byte outside the alphabet', () => {
  assert.throws(() => base32Decode('01')); // '0' and '1' are not in A-Z2-7
});

test('parseFragmentHeader: round-trips a hand-built header', () => {
  const { index, count, chunk } = parseFragmentHeader('00' + '02' + 'ABCXYZ');
  assert.equal(index, 0);
  assert.equal(count, 2);
  assert.equal(chunk, 'ABCXYZ');
});

test('parseFragmentHeader: rejects index >= count', () => {
  assert.throws(() => parseFragmentHeader('02' + '02' + 'ABC'));
});

test('stripUrl: strips the exact scheme+base+path-separator prefix', () => {
  const url = 'HTTPS://SM64NOSTR.PAGES.DEV/0002HELLO';
  assert.equal(stripUrl(url, 'SM64NOSTR.PAGES.DEV'), '0002HELLO');
});

test('stripUrl: rejects a URL for a different base', () => {
  assert.throws(() => stripUrl('HTTPS://EXAMPLE.COM/0002HELLO', 'SM64NOSTR.PAGES.DEV'));
});

// --- The keystone round-trip: the fixture's REAL frames, byte-identical
// reassembly (spec #115's own acceptance criterion). ---

test('reassembleFrames: the fixture frame count matches its own header claims', () => {
  const { complete, base32Text } = reassembleFrames(fixture.frames, fixture.urlBase);
  assert.ok(complete, 'expected the natural-order frame set to be reported complete');
  assert.equal(fixture.frames.length, fixture.frameCount);
  const bytes = base32Decode(base32Text);
  assert.equal(bytesToHex(bytes), fixture.packedPayloadHex,
    'reassembled bytes must be byte-identical to build_event\'s own packed_payload');
});

test('reassembleFrames: reverse frame order still reassembles byte-identically (any-order contract)', () => {
  const reversed = [...fixture.frames].reverse();
  const { complete, base32Text } = reassembleFrames(reversed, fixture.urlBase);
  assert.ok(complete);
  assert.equal(bytesToHex(base32Decode(base32Text)), fixture.packedPayloadHex);
});

test('reassembleFrames: a missing fragment reports incomplete, never a wrong/partial event', () => {
  if (fixture.frames.length < 2) {
    return; // this fixture is expected to be N>=2 (multiframe); skip defensively if it ever isn't
  }
  const partial = fixture.frames.slice(0, fixture.frames.length - 1);
  const result = reassembleFrames(partial, fixture.urlBase);
  assert.equal(result.complete, false);
});

test('reassembleFrames: rejects fragments from two different broadcasts with mismatched chunk lengths', () => {
  // Same frame count (3), same base URL -- but frame 0's chunk is 5 chars
  // and frame 1's (also non-last) chunk is 6, which src/pipeline/fragment.c's
  // pipeline_fragment_build() can never produce for a single build_event()
  // call (every non-last fragment shares the same chunkCap length). This is
  // the "two different broadcasts happened to share a frame count" case
  // reassembleFrames must refuse to silently splice together.
  const prefix = `HTTPS://${fixture.urlBase}/`;
  const frames = [`${prefix}0003AAAAA`, `${prefix}0103BBBBBB`, `${prefix}0203C`];
  assert.throws(() => reassembleFrames(frames, fixture.urlBase), /inconsistent non-last chunk length/);
});

test('reassembleFrames: rejects a last fragment longer than the shared non-last chunk length', () => {
  const prefix = `HTTPS://${fixture.urlBase}/`;
  const frames = [`${prefix}0002AAAAA`, `${prefix}0102BBBBBBBBBB`]; // last (index 1) longer than index 0
  assert.throws(() => reassembleFrames(frames, fixture.urlBase), /last fragment is longer/);
});

test('reassembleFrames: a duplicated frame is harmless (idempotent by index)', () => {
  const withDup = [...fixture.frames, fixture.frames[0]];
  const { complete, base32Text } = reassembleFrames(withDup, fixture.urlBase);
  assert.ok(complete);
  assert.equal(bytesToHex(base32Decode(base32Text)), fixture.packedPayloadHex);
});

// --- Decode the reassembled bytes via the shared descriptor. ---

// Reassembly is already covered above; every test past this point that
// needs the reassembled+unpacked payload recomputes it fresh (no shared
// mutable state / hidden test-order dependency).
function reassembleAndUnpack() {
  const bytes = base32Decode(reassembleFrames(fixture.frames, fixture.urlBase).base32Text);
  return unpackPayload(bytes);
}

test('unpackPayload: recovers every wire field verbatim, matching the fixture exactly', () => {
  const unpacked = reassembleAndUnpack();
  assert.equal(unpacked.COURSE, fixture.capture.course);
  assert.equal(unpacked.ACT, fixture.capture.act);
  assert.equal(unpacked.COINS, fixture.capture.coins);
  assert.equal(unpacked.FRAMES, fixture.capture.frames);
  assert.equal(unpacked.NONCE16, fixture.capture.nonce16);
  assert.equal(unpacked.KEY_ID, fixture.capture.keyId);
  assert.equal(unpacked.CREATED_AT, fixture.createdAt);
  assert.equal(unpacked.PUBKEY, fixture.pubkeyHex);
  assert.equal(unpacked.TAG, fixture.tag);
  assert.equal(unpacked.NAME, fixture.name);
  assert.equal(unpacked.SIG, fixture.sigHex);
});

test('unpackPayload: rejects a payload with a corrupted FORMAT_TAG byte', () => {
  const bytes = base32Decode(reassembleFrames(fixture.frames, fixture.urlBase).base32Text);
  const corrupted = new Uint8Array(bytes);
  corrupted[0] = 0x02; // the retired format v2 tag
  assert.throws(() => unpackPayload(corrupted));
});

// --- Recompute ONLY `id`; every other field is the verbatim wire value. ---

test('computeEventId: recomputes the exact id build_event itself signed', () => {
  const unpacked = reassembleAndUnpack();
  const fields = buildCanonicalEventFields(unpacked);
  assert.equal(fields.pubkey, fixture.pubkeyHex, 'pubkey must be the verbatim wire value, never recomputed');
  assert.equal(fields.created_at, fixture.createdAt, 'created_at must be the verbatim wire value, never recomputed');
  assert.equal(buildContentJson(unpacked), JSON.stringify({
    course: fixture.capture.course, act: fixture.capture.act, coins: fixture.capture.coins,
    frames: fixture.capture.frames, nonce: fixture.capture.nonce16, keyId: fixture.capture.keyId,
  }), 'content must be built solely from the verbatim wire capture fields');

  const id = computeEventId(fields);
  assert.equal(id, fixture.expectedIdHex);
});

test('decodeToBroadcastEvent: end-to-end -- every field but `id` is the verbatim wire value', () => {
  const bytes = base32Decode(reassembleFrames(fixture.frames, fixture.urlBase).base32Text);
  const event = decodeToBroadcastEvent(bytes);

  assert.equal(event.id, fixture.expectedIdHex);
  assert.equal(event.pubkey, fixture.pubkeyHex);
  assert.equal(event.created_at, fixture.createdAt);
  assert.equal(event.kind, 8064);
  assert.deepEqual(event.tags, [['t', 'ag-lb'], ['t', fixture.tag], ['n', fixture.name]]);
  assert.equal(event.sig, fixture.sigHex, 'sig must be the verbatim wire value -- NEVER recomputed or signed here');
});

test('zero far-side reconstruction: reader.js imports no signing primitive and takes no key', () => {
  // Structural guard, not just a behavioral one: assert the module source
  // itself contains no signing-capable API surface, so a future change
  // cannot silently reintroduce far-side reconstruction (ADR-0005/ADR-0006).
  const readerSrc = readFileSync(path.join(__dirname, '..', 'reader.js'), 'utf8');
  const forbidden = [/schnorr\.sign/i, /\bsign\s*\(/i, /privateKey/i, /getPublicKey/i, /\bprivkey\b/i];
  for (const pattern of forbidden) {
    assert.ok(!pattern.test(readerSrc), `reader.js must not reference ${pattern} -- it must never be able to sign`);
  }
});

test('buildRelayMessage: builds the exact NIP-01 ["EVENT", event] publish frame', () => {
  const bytes = base32Decode(reassembleFrames(fixture.frames, fixture.urlBase).base32Text);
  const event = decodeToBroadcastEvent(bytes);
  const message = buildRelayMessage(event);
  const parsed = JSON.parse(message);
  assert.equal(parsed[0], 'EVENT');
  assert.deepEqual(parsed[1], event);
});

// --- Independent oracles (mirrors tools/reference_event_id.js's own
// "genuinely independent library" convention): nostr-tools' getEventHash()
// for the id, @noble/curves' schnorr.verify for the signature. Neither is
// imported by reader.js itself -- these run only in this test file, so the
// shipped reader page never depends on them. ---

test('independent oracle: nostr-tools getEventHash agrees with computeEventId', async () => {
  const { getEventHash } = await import('nostr-tools');
  const fields = buildCanonicalEventFields(reassembleAndUnpack());
  const oracleId = getEventHash({
    pubkey: fields.pubkey, created_at: fields.created_at, kind: fields.kind,
    tags: fields.tags, content: fields.content,
  });
  assert.equal(oracleId, fixture.expectedIdHex);
  assert.equal(oracleId, computeEventId(fields));
});

test('independent oracle: the broadcast event\'s signature genuinely verifies (@noble/curves)', async () => {
  const { schnorr } = await import('@noble/curves/secp256k1.js');
  const bytes = base32Decode(reassembleFrames(fixture.frames, fixture.urlBase).base32Text);
  const event = decodeToBroadcastEvent(bytes);
  const ok = schnorr.verify(hexToBytes(event.sig), hexToBytes(event.id), hexToBytes(event.pubkey));
  assert.ok(ok, 'the reassembled event\'s wire-carried signature must verify against the recomputed id');
});

test('sha256Hex: cross-checked against node:crypto (an independent SHA-256 implementation)', async () => {
  const { createHash } = await import('node:crypto');
  const { sha256Hex } = await import('../sha256.js');
  const samples = ['', 'abc', 'the quick brown fox', JSON.stringify([0, 'x', 1, 2, [], '{}'])];
  for (const s of samples) {
    const expected = createHash('sha256').update(s, 'utf8').digest('hex');
    assert.equal(sha256Hex(s), expected, `sha256Hex(${JSON.stringify(s)})`);
  }
});
