// Regenerates the live golden vectors from the raw QR wire bytes (the only
// input). Decodes per format v2, reconstructs the broadcast-ready event, and
// records schnorr sig_ok so the outputs are self-certifying. Emits BOTH:
//   - qr_v2_live_captures.json : human/tooling-facing (wire hex + full event)
//   - live_vectors.h           : consumed by main.c's C round-trip test
// so the JSON and the C test share ONE source of truth. Run:
//   node tools/pipeline_test/fixtures/gen_live_vectors.mjs
import { getEventHash } from 'nostr-tools/pure';
import { schnorr } from '@noble/curves/secp256k1.js';
import { writeFileSync } from 'node:fs';

// Live captures from an on-device v2 build (format_tag 0x02), pasted from the
// on-screen QR. These are the real wire bytes crossing the airgap.
const WIRE = {
  capture_1: "0213001a000010104c98016aa07818cced8051ec3487aa359db9ddac08068961ecdc57dab545bd80cc0f8385a789bf04736d3634be212fed088be4db4d4d2a8a328ec11429fc69f4254f1588926868fa712f86ccafed52646e28dcbb6a3a7957afaa22e77ad8db2ce4399f6ec359410b1602102e",
  capture_2: "02010100000031d8900c006aa07818cced8051ec3487aa359db9ddac08068961ecdc57dab545bd80cc0f8385a789bf04736d3634200defae9217ace0dce7a640e7bd295b68225991ac096716f102bb07817066d1cc4d9a8e8bcde3f77942a3ec3c31f04b1e9e2015d21ee21c5bbe3be8fb2d0266",
};
const hex = b => Buffer.from(b).toString('hex');
function decode(h) {
  const b = Buffer.from(h, 'hex');
  if (b[0] !== 0x02) throw new Error(`FORMAT_TAG != 0x02 (got 0x${b[0].toString(16)})`);
  const rd = o => b.readUInt32BE(o);
  const course=b[1], act=b[2], coins=b[3], frames=rd(4), nonce=b.readUInt16BE(8), keyId=b[10];
  const created=rd(11), pub=b.subarray(15,47), tagLen=b[47];
  if (tagLen > 10) throw new Error(`TAG_LEN ${tagLen} > 10`);
  if (b.length !== 112 + tagLen) throw new Error(`len ${b.length} != 112+${tagLen}`);
  const tag=b.subarray(48,48+tagLen).toString('ascii');
  const sig=b.subarray(48+tagLen,48+tagLen+64);
  const content=JSON.stringify({course,act,coins,frames,nonce,keyId});
  const ev={pubkey:hex(pub),created_at:created,kind:8064,tags:[["t","ag-lb"],["t",tag]],content};
  const id=getEventHash(ev);
  const sig_ok=schnorr.verify(sig,Buffer.from(id,'hex'),pub);
  return { event:{id,...ev,sig:hex(sig)}, sig_ok };
}
const vectors = Object.entries(WIRE).map(([name,wire_hex]) => {
  const { event, sig_ok } = decode(wire_hex);
  if (!sig_ok) throw new Error(`${name}: sig FAILED to verify — refusing to write a bad vector`);
  return { name, wire_hex, wire_len_bytes: wire_hex.length/2, sig_ok, event };
});
const out = {
  _comment: "Golden test vectors: real format-v2 QR wire bytes captured from an on-device build, each paired with the exact broadcast-ready Nostr event it decodes to. Build architecture and companion decoders against THIS, not inferred data. Regenerate: node tools/pipeline_test/fixtures/gen_live_vectors.mjs. Each event's sig is verified (sig_ok) at generation time; generation aborts if any sig fails.",
  format: "v2",
  source: "on-device capture, spec #52 / PR #56",
  vectors,
};
writeFileSync(new URL('./qr_v2_live_captures.json', import.meta.url), JSON.stringify(out,null,2)+'\n');

// --- C header emit ------------------------------------------------------
// A minimal golden assertion needs only the wire bytes and the expected id:
// main.c re-derives pubkey/tag/sig from the wire via pipeline_unpack(), then
// recomputes the id and verifies the sig. Emitting the id (not pubkey/sig)
// keeps the C side asserting the reconstruction, not just echoing bytes.
const cBytes = b => Array.from(b, x => `0x${x.toString(16).padStart(2,'0')}`);
const cArray = (b, per=12) => {
  const t = cBytes(b);
  const lines = [];
  for (let i=0;i<t.length;i+=per) lines.push('    ' + t.slice(i,i+per).join(', ') + ',');
  return lines.join('\n');
};
let h = `/*
 * GENERATED by tools/pipeline_test/fixtures/gen_live_vectors.mjs -- DO NOT EDIT.
 * Real format-v2 QR wire bytes captured on-device (spec #52 / PR #56), each
 * paired with the id the reconstructed event must hash to. Sibling of
 * qr_v2_live_captures.json (same generator, same source). Regenerate:
 *   node tools/pipeline_test/fixtures/gen_live_vectors.mjs
 * The generator verifies every sig before writing, so a committed vector
 * whose sig does not verify cannot exist.
 */
#ifndef PIPELINE_LIVE_VECTORS_H
#define PIPELINE_LIVE_VECTORS_H

typedef struct {
    const char *name;
    const unsigned char *wire;
    unsigned int wire_len;
    const unsigned char *expected_id; /* 32 bytes */
} PipelineLiveVector;

`;
for (const v of vectors) {
  const wire = Buffer.from(v.wire_hex, 'hex');
  const id = Buffer.from(v.event.id, 'hex');
  h += `static const unsigned char k_${v.name}_wire[${wire.length}] = {\n${cArray(wire)}\n};\n`;
  h += `static const unsigned char k_${v.name}_id[32] = {\n${cArray(id)}\n};\n\n`;
}
h += `static const PipelineLiveVector k_pipeline_live_vectors[${vectors.length}] = {\n`;
for (const v of vectors) {
  const wire = Buffer.from(v.wire_hex, 'hex');
  h += `    { "${v.name}", k_${v.name}_wire, ${wire.length}, k_${v.name}_id },\n`;
}
h += `};\n#define PIPELINE_LIVE_VECTOR_COUNT ${vectors.length}u\n\n#endif /* PIPELINE_LIVE_VECTORS_H */\n`;
writeFileSync(new URL('./live_vectors.h', import.meta.url), h);

console.log(`wrote ${vectors.length} vectors (json + live_vectors.h), all sig_ok=${vectors.every(v=>v.sig_ok)}`);
