/*
 * reader.js -- the airgap jumper's decode/reassemble/broadcast logic (spec
 * #115, sub-issue #119; ADR-0005/ADR-0006's reader model). Every function
 * here is pure (no DOM, no camera, no network) so it can be exercised by
 * reader/test/reader.test.mjs without a browser or a live relay --
 * index.html (the actual page a phone camera opens) wires these to
 * getUserMedia + jsQR (camera capture) and a WebSocket (relay broadcast),
 * neither of which lives in this file.
 *
 * Derives its wire-format knowledge ENTIRELY from reader/generated/
 * transport_contract.js -- itself generated by tools/gen_transport_contract_js.py
 * from the same src/pipeline/transport_contract.h, src/pipeline/event_id.h,
 * and src/pipeline/format_descriptor.json the cabinet-side C pipeline
 * derives from -- never a hand-copied literal. See that file's own header
 * comment.
 *
 * Zero far-side reconstruction (ADR-0005/ADR-0006): every PER-EVENT value
 * in the broadcast event -- pubkey, created_at, tags[1] (the per-game tag),
 * tags[2] (the event name), content, sig -- is recovered VERBATIM from the
 * decoded wire bytes. `kind` and tags[0] (["t","ag-lb"]) are format-v3-pinned
 * PUBLIC SPEC CONSTANTS, identical for every build (event_id.h's own
 * PIPELINE_EVENT_KIND/PIPELINE_EVENT_TAG0_VALUE, ported into
 * transport_contract.js) -- exactly like every other NIP-01 reader already
 * has to know `kind`/tag shape out of band from the spec itself, not data
 * this code invents per event; a build whose actual wire bytes disagree
 * with these constants is already rejected upstream by FORMAT_TAG (this
 * repo publishes exactly one wire format per FORMAT_TAG value). The ONLY
 * value derived FROM this event's own bytes is `id`, a SHA-256 checksum of
 * bytes already fully determined by the wire payload (computeEventId()
 * below) -- never a default, never a guess, never a value this code
 * invents. No function in this file accepts a private key, and no signing
 * primitive is imported anywhere in this module -- there is nothing here
 * CAPABLE of fabricating a signature, by construction.
 */

import { TRANSPORT_CONTRACT, FORMAT_DESCRIPTOR } from './generated/transport_contract.js';
import { sha256Hex, bytesToHex, hexToBytes } from './sha256.js';

const {
  PIPELINE_BASE32_ALPHABET,
  PIPELINE_FRAGMENT_BASE36_ALPHABET,
  PIPELINE_URL_FIELD_SEP,
  PIPELINE_URL_FRAGMENT_SEP,
  PIPELINE_FRAGMENT_INDEX_LEN,
  PIPELINE_FRAGMENT_COUNT_LEN,
  PIPELINE_EVENT_TAG_KEY,
  PIPELINE_EVENT_TAG0_VALUE,
  PIPELINE_EVENT_NAME_TAG_KEY,
  PIPELINE_EVENT_KIND,
} = TRANSPORT_CONTRACT;

// PIPELINE_FRAGMENT_INDEX_LEN base36 digits, then PIPELINE_URL_FIELD_SEP,
// then PIPELINE_FRAGMENT_COUNT_LEN base36 digits, then another
// PIPELINE_URL_FIELD_SEP -- e.g. "00/02/" -- ahead of the base32 chunk
// (spec #122's ratified <SEQ>/<TOTAL>/<PAYLOAD> template).
const COUNT_FIELD_START = PIPELINE_FRAGMENT_INDEX_LEN + PIPELINE_URL_FIELD_SEP.length;
const FRAGMENT_HEADER_LEN = COUNT_FIELD_START + PIPELINE_FRAGMENT_COUNT_LEN + PIPELINE_URL_FIELD_SEP.length;

/**
 * base32Decode: the exact inverse of src/pipeline/base32.c's
 * pipeline_base32_encode() -- RFC 4648 section 6, uppercase A-Z2-7, no
 * padding, MSB-first bit packing. Returns a Uint8Array, or throws if any
 * character is outside PIPELINE_BASE32_ALPHABET.
 */
export function base32Decode(text) {
  const out = [];
  let bitBuf = 0;
  let bitCount = 0;
  for (let i = 0; i < text.length; i++) {
    const value = PIPELINE_BASE32_ALPHABET.indexOf(text[i]);
    if (value < 0) {
      throw new Error(`base32Decode: byte outside PIPELINE_BASE32_ALPHABET at offset ${i}: ${text[i]}`);
    }
    bitBuf = (bitBuf << 5) | value;
    bitCount += 5;
    if (bitCount >= 8) {
      bitCount -= 8;
      out.push((bitBuf >>> bitCount) & 0xff);
    }
    bitBuf &= bitCount > 0 ? (1 << bitCount) - 1 : 0;
  }
  return new Uint8Array(out);
}

/**
 * parseFragmentHeader: the exact port of src/pipeline/fragment.c's
 * pipeline_fragment_parse_header() -- reads fragment[0:FRAGMENT_HEADER_LEN]
 * (PIPELINE_FRAGMENT_INDEX_LEN base36 digits, PIPELINE_URL_FIELD_SEP,
 * PIPELINE_FRAGMENT_COUNT_LEN base36 digits, PIPELINE_URL_FIELD_SEP -- e.g.
 * "00/02/", spec #122's ratified <SEQ>/<TOTAL>/<PAYLOAD> template) and
 * returns { index, count, chunk }, where chunk is fragment's remaining text
 * (the base32 slice). Throws if the fragment is too short, either
 * PIPELINE_URL_FIELD_SEP separator is missing/wrong, either base36 field
 * has a non-base36 byte, count is 0, or index >= count -- a structurally
 * invalid header, never guessed at.
 */
export function parseFragmentHeader(fragment) {
  if (fragment.length < FRAGMENT_HEADER_LEN) {
    throw new Error('parseFragmentHeader: fragment shorter than the header');
  }
  if (fragment[PIPELINE_FRAGMENT_INDEX_LEN] !== PIPELINE_URL_FIELD_SEP
      || fragment[COUNT_FIELD_START + PIPELINE_FRAGMENT_COUNT_LEN] !== PIPELINE_URL_FIELD_SEP) {
    throw new Error(`parseFragmentHeader: missing/wrong '${PIPELINE_URL_FIELD_SEP}' field separator in header`);
  }
  const indexField = fragment.slice(0, PIPELINE_FRAGMENT_INDEX_LEN);
  const countField = fragment.slice(COUNT_FIELD_START, COUNT_FIELD_START + PIPELINE_FRAGMENT_COUNT_LEN);
  const index = decodeBase36Field(indexField);
  const count = decodeBase36Field(countField);
  if (count === 0 || index >= count) {
    throw new Error(`parseFragmentHeader: structurally invalid header (index=${index}, count=${count})`);
  }
  return { index, count, chunk: fragment.slice(FRAGMENT_HEADER_LEN) };
}

function decodeBase36Field(field) {
  let value = 0;
  for (const ch of field) {
    const digit = PIPELINE_FRAGMENT_BASE36_ALPHABET.indexOf(ch);
    if (digit < 0) {
      throw new Error(`decodeBase36Field: byte outside the base36 alphabet: ${ch}`);
    }
    value = value * PIPELINE_FRAGMENT_BASE36_ALPHABET.length + digit;
  }
  return value;
}

/**
 * extractFragment: the host-agnostic port of src/pipeline/url.c's
 * pipeline_url_extract_fragment() (spec #122, sub-issue #123) -- recovers
 * everything after the FIRST PIPELINE_URL_FRAGMENT_SEP ('#') byte in url,
 * with NO comparison against any expected base URL at all: a frame wrapped
 * around ANY base, served from ANY host, extracts identically. This is
 * "split once on `#`", nothing more -- host-independence is structural,
 * not a configuration a deployer could get wrong (there is no baseUrl
 * parameter to get wrong). Throws if url contains no `#` at all.
 */
export function extractFragment(url) {
  const sepIndex = url.indexOf(PIPELINE_URL_FRAGMENT_SEP);
  if (sepIndex < 0) {
    throw new Error(`extractFragment: ${JSON.stringify(url)} contains no '${PIPELINE_URL_FRAGMENT_SEP}' fragment separator`);
  }
  return url.slice(sepIndex + PIPELINE_URL_FRAGMENT_SEP.length);
}

/**
 * reassembleFrames: the "opened webpage" half of ADR-0006's transport
 * (spec #115, sub-issue #116/#119; host-agnostic per spec #122 sub-issue
 * #123) -- the JS twin of tools/pipeline_test/main.c's
 * reassemble_built_event(). Takes frameUrls (an array of raw URL strings,
 * one per scanned frame, in ANY order -- exactly what a stock camera hands
 * back one frame at a time), extracts + parses each one's fragment with NO
 * base-URL argument and NO host comparison whatsoever, and concatenates
 * chunks at their own header-declared index. Returns
 * { complete: true, base32Text } once every index 0..count-1 has been seen
 * at least once; returns { complete: false, seen, count } otherwise -- an
 * incomplete set is reported as incomplete, NEVER as a wrong/partial
 * reassembly (the same invariant the C reassembler enforces).
 *
 * A partial same-count session/batch discriminator: src/pipeline/fragment.c's
 * pipeline_fragment_build() always slices every fragment but the last to
 * the SAME chunkCap length (only the final index may be shorter -- see
 * that function's own `end = start + chunkCap, capped at base32Len`), so
 * every non-last chunk length seen here must agree, and the last chunk can
 * never be longer than that. This catches two interleaved broadcasts that
 * share a frame count but differ in packed-payload length (a different
 * tag/name length, the common case for two different runs); it can NOT
 * catch two broadcasts that happen to share BOTH frame count AND every
 * chunk length exactly (identical tag/name lengths, different content) --
 * that residual case is caught downstream, not here: the reassembled
 * bytes' signature (checked by decodeToBroadcastEvent()'s caller/the
 * relay, never by this function) would fail to verify against a payload
 * spliced from two different signed events. A mismatch this function DOES
 * catch throws rather than silently concatenating fragments from two
 * different events into one payload.
 */
export function reassembleFrames(frameUrls) {
  const chunksByIndex = new Map();
  let count = null;
  let nonLastChunkLen = null;

  for (const url of frameUrls) {
    const fragment = extractFragment(url);
    const { index, count: frameCount, chunk } = parseFragmentHeader(fragment);
    if (count === null) {
      count = frameCount;
    } else if (count !== frameCount) {
      throw new Error(`reassembleFrames: inconsistent frame count across frames (${count} vs ${frameCount})`);
    }
    if (index < frameCount - 1) {
      if (nonLastChunkLen === null) {
        nonLastChunkLen = chunk.length;
      } else if (nonLastChunkLen !== chunk.length) {
        throw new Error('reassembleFrames: inconsistent non-last chunk length across frames -- '
          + 'refusing to mix fragments from two different broadcasts');
      }
    }
    if (!chunksByIndex.has(index)) {
      chunksByIndex.set(index, chunk);
    }
  }

  if (count === null) {
    return { complete: false, seen: 0, count: 0 };
  }
  if (chunksByIndex.size !== count) {
    return { complete: false, seen: chunksByIndex.size, count };
  }
  if (nonLastChunkLen !== null && chunksByIndex.get(count - 1).length > nonLastChunkLen) {
    throw new Error('reassembleFrames: last fragment is longer than a non-last fragment -- '
      + 'refusing to mix fragments from two different broadcasts');
  }

  let base32Text = '';
  for (let i = 0; i < count; i++) {
    base32Text += chunksByIndex.get(i);
  }
  return { complete: true, base32Text };
}

/**
 * unpackPayload: a GENERIC reader of the packed wire payload, walking
 * FORMAT_DESCRIPTOR.fields in order exactly like tools/gen_format_descriptor.py's
 * offset derivation (a fixed running offset, plus each already-read
 * variable field's own runtime length) -- so this function never
 * hand-codes format v3's specific field list; it reads whichever fields
 * format_descriptor.json actually describes. Rejects (throws) if
 * FORMAT_TAG doesn't match FORMAT_DESCRIPTOR.format_tag, or if any
 * var_len field's runtime length exceeds its own max_size, or if the
 * decoded field layout doesn't exactly consume bytes.length -- mirroring
 * src/pipeline/pack_adapter.c's pipeline_unpack() own rejection contract
 * (reject, don't guess).
 *
 * Returns a plain object keyed by field name: fixed-size numeric fields as
 * numbers (big-endian multi-byte), PUBKEY/SIG as hex strings, TAG/NAME as
 * ASCII strings (their charset is fixed to the QR alphanumeric/HUD-glyph
 * charset upstream, so plain ASCII decode is exact -- see event_id.c's own
 * comment on why TAG/NAME need no JSON-style escaping).
 */
export function unpackPayload(bytes) {
  const fields = FORMAT_DESCRIPTOR.fields;
  const out = {};
  let offset = 0;

  for (const field of fields) {
    let size;
    if (field.var_len) {
      size = out[field.len_field];
      if (typeof size !== 'number') {
        throw new Error(`unpackPayload: var_len field ${field.name} references unknown len_field ${field.len_field}`);
      }
      if (size > field.max_size) {
        throw new Error(`unpackPayload: ${field.name} length ${size} exceeds max_size ${field.max_size}`);
      }
    } else {
      size = field.size;
    }
    if (offset + size > bytes.length) {
      throw new Error(`unpackPayload: payload too short for field ${field.name}`);
    }
    out[field.name] = readField(field, bytes, offset, size);
    offset += size;
  }

  if (offset !== bytes.length) {
    throw new Error(`unpackPayload: payload length ${bytes.length} does not match total decoded size ${offset}`);
  }
  if (out.FORMAT_TAG !== FORMAT_DESCRIPTOR.format_tag) {
    throw new Error(`unpackPayload: FORMAT_TAG ${out.FORMAT_TAG} != expected ${FORMAT_DESCRIPTOR.format_tag}`);
  }

  return out;
}

function readField(field, bytes, offset, size) {
  const slice = bytes.subarray(offset, offset + size);
  // field.encoding is format_descriptor.json's own metadata (see that
  // file's header comment) -- driven by the SAME shared descriptor the C
  // pack/unpack adapters read, never a second, hand-copied field-name
  // allowlist in this file.
  if (field.encoding === 'hex') {
    return bytesToHex(slice);
  }
  if (field.encoding === 'ascii') {
    return new TextDecoder('ascii').decode(slice);
  }
  // Default: a big-endian unsigned integer of `size` bytes. size <= 4 for
  // every such field today, so plain JS number math (safe up to 2^53)
  // never loses precision.
  let value = 0;
  for (let i = 0; i < size; i++) {
    value = value * 256 + slice[i];
  }
  return value;
}

/**
 * buildContentJson: the exact port of event_id.c's
 * pipeline_event_build_content() -- fixed key order (course, act, coins,
 * frames, nonce, keyId), matching event_id.h's own documented content
 * shape. Built with JSON.stringify over a plain object with that exact key
 * order (JS preserves non-numeric-string key insertion order), the same
 * convention tools/reference_event_id.js and
 * tools/pipeline_test/fixtures/gen_live_vectors.mjs already use as their
 * own independent JS oracle for this content shape.
 */
export function buildContentJson(unpacked) {
  return JSON.stringify({
    course: unpacked.COURSE,
    act: unpacked.ACT,
    coins: unpacked.COINS,
    frames: unpacked.FRAMES,
    nonce: unpacked.NONCE16,
    keyId: unpacked.KEY_ID,
  });
}

/**
 * buildCanonicalEventFields: recovers every value the signed NIP-01
 * serialization needs -- pubkey, created_at, kind, tags, content -- purely
 * from unpackPayload()'s wire fields plus the two format-v3-pinned spec
 * constants (kind, tag0) transport_contract.js also carries (from
 * event_id.h). Mirrors event_id.c's pipeline_event_serialize_from_fields()
 * tag shape: [[t,TAG0],[t,tag],[n,name]]. Nothing here is invented: pubkey/
 * tag/name/content all come straight from `unpacked`.
 */
export function buildCanonicalEventFields(unpacked) {
  return {
    pubkey: unpacked.PUBKEY,
    created_at: unpacked.CREATED_AT,
    kind: PIPELINE_EVENT_KIND,
    tags: [
      [PIPELINE_EVENT_TAG_KEY, PIPELINE_EVENT_TAG0_VALUE],
      [PIPELINE_EVENT_TAG_KEY, unpacked.TAG],
      [PIPELINE_EVENT_NAME_TAG_KEY, unpacked.NAME],
    ],
    content: buildContentJson(unpacked),
  };
}

/**
 * serializeForId: the canonical NIP-01 serialization array
 * [0, pubkey, created_at, kind, tags, content], JSON.stringify'd with no
 * extra whitespace -- exactly nostr-tools' own getEventHash() algorithm
 * (see tools/reference_event_id.js's own header comment quoting it), which
 * is in turn exactly what event_id.c's pipeline_event_serialize_from_fields()
 * implements by hand in C.
 */
export function serializeForId(fields) {
  return JSON.stringify([0, fields.pubkey, fields.created_at, fields.kind, fields.tags, fields.content]);
}

/**
 * computeEventId: id = SHA256(serializeForId(fields)), hex-encoded. THE
 * ONLY derived value in this entire module (see this file's own header
 * comment on zero far-side reconstruction) -- a checksum of bytes already
 * fully determined by the decoded wire payload, never a value this code
 * invents.
 */
export function computeEventId(fields) {
  return sha256Hex(serializeForId(fields));
}

/**
 * decodeToBroadcastEvent: the full far-side chain -- unpack the reassembled
 * packed bytes, recover the canonical event fields verbatim, recompute
 * ONLY `id`, and attach the wire's own `sig` (also recovered verbatim,
 * never recomputed -- there is no signing primitive anywhere in this
 * module). Returns a complete NIP-01 event object ready to broadcast:
 * { id, pubkey, created_at, kind, tags, content, sig }.
 */
export function decodeToBroadcastEvent(packedBytes) {
  const unpacked = unpackPayload(packedBytes);
  const fields = buildCanonicalEventFields(unpacked);
  const id = computeEventId(fields);
  return {
    id,
    pubkey: fields.pubkey,
    created_at: fields.created_at,
    kind: fields.kind,
    tags: fields.tags,
    content: fields.content,
    sig: unpacked.SIG,
  };
}

/**
 * buildRelayMessage: the exact NIP-01 client->relay publish frame,
 * `["EVENT", event]`, JSON.stringify'd -- a pure function of the event
 * object, so it can be asserted deterministically without opening a
 * WebSocket (index.html sends this string over a real socket; tests only
 * ever call this function).
 */
export function buildRelayMessage(event) {
  return JSON.stringify(['EVENT', event]);
}

export { hexToBytes, bytesToHex };
