#!/usr/bin/env python3
"""
Render the packed-payload format descriptor (spec #24, sub-issue #26) from
its single JSON source (src/pipeline/format_descriptor.json) into a C
header. Run twice -- once for the ROM build (into $(BUILD_DIR)/include) and
once for the host test tool (into tools/pipeline_test/build/include) -- from
the identical JSON input, so the ROM pack adapter and the host unpack
adapter can never disagree on field offsets/sizes. This mirrors the
"same pure source compiled twice" precedent from sub-issue #25, applied to
a generated header instead of a hand-written .c file.

Usage: gen_format_descriptor.py --json <path> --out <path>
"""
import argparse
import json
import os
import sys


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--json", required=True)
    ap.add_argument("--out", required=True)
    args = ap.parse_args()

    with open(args.json, "r") as f:
        descriptor = json.load(f)

    fields = descriptor["fields"]
    format_tag = descriptor["format_tag"]

    offset = 0
    rendered_fields = []
    for field in fields:
        name = field["name"]
        size = field["size"]
        rendered_fields.append((name, offset, size))
        offset += size
    total_size = offset

    lines = []
    lines.append("#ifndef PIPELINE_FORMAT_DESCRIPTOR_H")
    lines.append("#define PIPELINE_FORMAT_DESCRIPTOR_H")
    lines.append("")
    lines.append("/*")
    lines.append(" * GENERATED by tools/gen_format_descriptor.py from the single-source")
    lines.append(" * descriptor src/pipeline/format_descriptor.json -- DO NOT EDIT (spec #24,")
    lines.append(" * sub-issue #26). Both the ROM pack adapter and the host unpack adapter")
    lines.append(" * include this generated header (rendered separately into each build's")
    lines.append(" * own include dir from the identical JSON), so field offsets/sizes can")
    lines.append(" * never drift between the two sides of the QR payload seam.")
    lines.append(" */")
    lines.append("")
    lines.append("#define PIPELINE_FMT_TAG_VALUE %uu" % format_tag)
    lines.append("#define PIPELINE_FMT_FIELD_COUNT %uu" % len(rendered_fields))
    lines.append("#define PIPELINE_FMT_TOTAL_SIZE %uu" % total_size)
    lines.append("")
    for name, off, size in rendered_fields:
        lines.append("#define PIPELINE_FMT_OFF_%s  %uu" % (name, off))
        lines.append("#define PIPELINE_FMT_SIZE_%s %uu" % (name, size))
    lines.append("")
    lines.append("#endif /* PIPELINE_FORMAT_DESCRIPTOR_H */")
    lines.append("")

    os.makedirs(os.path.dirname(os.path.abspath(args.out)), exist_ok=True)
    with open(args.out, "w") as f:
        f.write("\n".join(lines))


if __name__ == "__main__":
    sys.exit(main())
