#!/usr/bin/env python3
"""
Render the packed-payload format descriptor (spec #24, sub-issue #26; format
v2 variable-length tag support added for spec #52, sub-issue #54) from its
single JSON source (src/pipeline/format_descriptor.json) into a C header.
Run twice -- once for the ROM build (into $(BUILD_DIR)/include) and once for
the host test tool (into tools/pipeline_test/build/include) -- from the
identical JSON input, so the ROM pack adapter and the host unpack adapter can
never disagree on field offsets/sizes. This mirrors the "same pure source
compiled twice" precedent from sub-issue #25, applied to a generated header
instead of a hand-written .c file.

Format v2 adds support for AT MOST ONE variable-length field (the per-game
TAG, len-prefixed by TAG_LEN): a field descriptor with "var_len": true,
"len_field" (the name of the fixed-size field elsewhere in the layout whose
runtime VALUE gives this field's actual length), and "max_size" (the largest
that length can legally be, used to size host-side decode buffers and the
compile-time QR-fits guard). Fields BEFORE the variable field get plain
fixed offsets, exactly as before. Fields AFTER it (only SIG, today) cannot
have a fixed compile-time offset -- their real position depends on the
variable field's runtime length -- so the generator instead emits their
offset as a function-like macro taking that runtime length, e.g.
PIPELINE_FMT_OFF_SIG(tagLen). PIPELINE_FMT_FIXED_SIZE is the total size
assuming the variable field contributes zero bytes (112 B for today's
layout); PIPELINE_FMT_TOTAL_SIZE(tagLen) is the real total for a given
runtime tag length, and PIPELINE_FMT_MAX_TOTAL_SIZE is the worst-case total
(112 + max_size), the right size for host-side decode/scratch buffers that
must hold any legal incoming payload.

Usage: gen_format_descriptor.py --json <path> --out <path>
"""
import argparse
import json
import os
import sys


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--json", required=True)
    ap.add_argument("--out", required=True)
    args = ap.parse_args()

    with open(args.json, "r") as f:
        descriptor = json.load(f)

    fields = descriptor["fields"]
    format_tag = descriptor["format_tag"]

    offset = 0
    fixed_fields = []       # (name, offset, size) -- before the variable field
    var_field = None        # {"name", "offset", "len_field", "max_size"}
    dynamic_fields = []     # (name, extra_offset_from_var_end, size) -- after it
    dynamic_extra = 0

    for field in fields:
        name = field["name"]
        if field.get("var_len"):
            if var_field is not None:
                raise ValueError(
                    "gen_format_descriptor.py: only one variable-length "
                    "field is supported, found a second: %s" % name
                )
            var_field = {
                "name": name,
                "offset": offset,
                "len_field": field["len_field"],
                "max_size": field["max_size"],
            }
            continue

        size = field["size"]
        if var_field is None:
            fixed_fields.append((name, offset, size))
            offset += size
        else:
            dynamic_fields.append((name, dynamic_extra, size))
            dynamic_extra += size

    fixed_size = offset + dynamic_extra
    max_total_size = fixed_size + (var_field["max_size"] if var_field else 0)

    lines = []
    lines.append("#ifndef PIPELINE_FORMAT_DESCRIPTOR_H")
    lines.append("#define PIPELINE_FORMAT_DESCRIPTOR_H")
    lines.append("")
    lines.append("/*")
    lines.append(" * GENERATED by tools/gen_format_descriptor.py from the single-source")
    lines.append(" * descriptor src/pipeline/format_descriptor.json -- DO NOT EDIT (spec #24,")
    lines.append(" * sub-issue #26; format v2 variable-length tag, spec #52 sub-issue #54).")
    lines.append(" * Both the ROM pack adapter and the host unpack adapter include this")
    lines.append(" * generated header (rendered separately into each build's own include")
    lines.append(" * dir from the identical JSON), so field offsets/sizes can never drift")
    lines.append(" * between the two sides of the QR payload seam.")
    lines.append(" */")
    lines.append("")
    lines.append("#define PIPELINE_FMT_TAG_VALUE %uu" % format_tag)
    lines.append("#define PIPELINE_FMT_FIELD_COUNT %uu" % len(fields))
    lines.append("")

    for name, off, size in fixed_fields:
        lines.append("#define PIPELINE_FMT_OFF_%s  %uu" % (name, off))
        lines.append("#define PIPELINE_FMT_SIZE_%s %uu" % (name, size))

    if var_field is not None:
        lines.append("")
        lines.append("/* Variable-length field: %s's actual length is the runtime VALUE of" % var_field["name"])
        lines.append(" * %s (a fixed-size field above), capped at MAX_SIZE below. Its start" % var_field["len_field"])
        lines.append(" * offset is fixed; fields after it are not (see the OFF_*(tagLen)")
        lines.append(" * function-like macros below). */")
        lines.append("#define PIPELINE_FMT_OFF_%s      %uu" % (var_field["name"], var_field["offset"]))
        lines.append("#define PIPELINE_FMT_MAX_SIZE_%s %uu" % (var_field["name"], var_field["max_size"]))

    if dynamic_fields:
        lines.append("")
        lines.append("/* Fields after the variable-length field: their offset depends on its")
        lines.append(" * actual runtime length, so these are function-like macros, not plain")
        lines.append(" * offset constants -- callers must pass the actual (unpacked) TAG_LEN. */")
        for name, extra, size in dynamic_fields:
            if extra == 0:
                expr = "(PIPELINE_FMT_OFF_%s + (tagLen))" % var_field["name"]
            else:
                expr = "(PIPELINE_FMT_OFF_%s + (tagLen) + %uu)" % (var_field["name"], extra)
            lines.append("#define PIPELINE_FMT_OFF_%s(tagLen)  %s" % (name, expr))
            lines.append("#define PIPELINE_FMT_SIZE_%s %uu" % (name, size))

    lines.append("")
    lines.append("/* PIPELINE_FMT_FIXED_SIZE: total size with the variable field contributing")
    lines.append(" * zero bytes (i.e. the sum of every fixed-size field). PIPELINE_FMT_TOTAL_SIZE(tagLen)")
    lines.append(" * is the real total for a given runtime tag length; PIPELINE_FMT_MAX_TOTAL_SIZE")
    lines.append(" * is the worst-case total (tagLen at its max), the right bound for host-side")
    lines.append(" * decode/scratch buffers that must hold any legal incoming payload. */")
    lines.append("#define PIPELINE_FMT_FIXED_SIZE %uu" % fixed_size)
    if var_field is not None:
        lines.append("#define PIPELINE_FMT_TOTAL_SIZE(tagLen) (PIPELINE_FMT_FIXED_SIZE + (tagLen))")
        lines.append("#define PIPELINE_FMT_MAX_TOTAL_SIZE %uu" % max_total_size)
    else:
        lines.append("#define PIPELINE_FMT_TOTAL_SIZE %uu" % fixed_size)
        lines.append("#define PIPELINE_FMT_MAX_TOTAL_SIZE %uu" % fixed_size)
    lines.append("")
    lines.append("#endif /* PIPELINE_FORMAT_DESCRIPTOR_H */")
    lines.append("")

    os.makedirs(os.path.dirname(os.path.abspath(args.out)), exist_ok=True)
    with open(args.out, "w") as f:
        f.write("\n".join(lines))


if __name__ == "__main__":
    sys.exit(main())
