#!/usr/bin/env python3
"""
Render the reader page's (reader/, spec #115 sub-issue #119) shared
fragment/base32/URL/format-descriptor contract from the SAME single-source
files the cabinet-side C pipeline derives from -- never a hand-copied
literal:

  - src/pipeline/transport_contract.h -- the base32 alphabet, the fragment
    header layout, and the URL template pieces (ADR-0006, spec #115
    sub-issue #116). This generator extracts the handful of #define'd
    string/integer literals it needs by name (a small, explicit allowlist
    below -- not a general C preprocessor), so a future edit to one of
    those macros' VALUES here is regenerated, not silently stale.
  - src/pipeline/event_id.h -- the format-v3-pinned NIP-01 serialization
    spec constants (`kind`, the first tag's key/value, the name tag's key)
    that every build shares, never baked per-build data (see that header's
    own comment on why these live there and not in event_profile.h.in).
  - src/pipeline/format_descriptor.json -- the packed-payload wire layout
    (same JSON tools/gen_format_descriptor.py renders into the C side's
    format_descriptor.h), embedded here verbatim so the reader's own
    generic field-offset walk (reader/reader.js's unpackPayload()) can
    never disagree with the C pack/unpack adapters on field order/width.

transport_contract.h's own header comment documents why the reader page
must independently PORT these values (it is JavaScript, not a second
includer of a C header) -- this script is that port, automated instead of
hand-transcribed, so the values can never silently drift the way a
hand-copied literal could.

Usage: gen_transport_contract_js.py --out reader/generated/transport_contract.js
"""
import argparse
import json
import os
import re
import sys

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TRANSPORT_CONTRACT_H = os.path.join(REPO_ROOT, "src", "pipeline", "transport_contract.h")
EVENT_ID_H = os.path.join(REPO_ROOT, "src", "pipeline", "event_id.h")
FORMAT_DESCRIPTOR_JSON = os.path.join(REPO_ROOT, "src", "pipeline", "format_descriptor.json")

# The exact macros this generator ports, by name -- extending either list
# below is the only change needed to expose a new shared constant to the
# reader; nothing else in this script is transport_contract.h/event_id.h
# specific.
STRING_MACROS_FROM_TRANSPORT_CONTRACT = [
    "PIPELINE_BASE32_ALPHABET",
    "PIPELINE_FRAGMENT_BASE36_ALPHABET",
    "PIPELINE_URL_SCHEME",
    "PIPELINE_URL_PATH_SEP",
]
INT_MACROS_FROM_TRANSPORT_CONTRACT = [
    "PIPELINE_FRAGMENT_INDEX_LEN",
    "PIPELINE_FRAGMENT_COUNT_LEN",
]
STRING_MACROS_FROM_EVENT_ID = [
    "PIPELINE_EVENT_TAG_KEY",
    "PIPELINE_EVENT_TAG0_VALUE",
    "PIPELINE_EVENT_NAME_TAG_KEY",
]
INT_MACROS_FROM_EVENT_ID = [
    "PIPELINE_EVENT_KIND",
]


def _extract_string_macro(text, name, source_path):
    m = re.search(r'#define\s+%s\s+"((?:[^"\\]|\\.)*)"' % re.escape(name), text)
    if not m:
        raise SystemExit("gen_transport_contract_js.py: could not find #define %s in %s" % (name, source_path))
    # transport_contract.h/event_id.h's string macros are plain ASCII
    # literals with no C escape sequences beyond what a JS string literal
    # also accepts verbatim (the alphabets/scheme/tag keys are all
    # A-Z0-9:/ ), so no unescaping beyond what the JSON dump below already
    # handles is needed.
    return m.group(1)


def _extract_int_macro(text, name, source_path):
    m = re.search(r'#define\s+%s\s+(\d+)' % re.escape(name), text)
    if not m:
        raise SystemExit("gen_transport_contract_js.py: could not find #define %s in %s" % (name, source_path))
    return int(m.group(1))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", required=True)
    args = ap.parse_args()

    with open(TRANSPORT_CONTRACT_H, "r") as f:
        transport_contract_text = f.read()
    with open(EVENT_ID_H, "r") as f:
        event_id_text = f.read()
    with open(FORMAT_DESCRIPTOR_JSON, "r") as f:
        format_descriptor = json.load(f)

    contract = {}
    for name in STRING_MACROS_FROM_TRANSPORT_CONTRACT:
        contract[name] = _extract_string_macro(transport_contract_text, name, TRANSPORT_CONTRACT_H)
    for name in INT_MACROS_FROM_TRANSPORT_CONTRACT:
        contract[name] = _extract_int_macro(transport_contract_text, name, TRANSPORT_CONTRACT_H)
    for name in STRING_MACROS_FROM_EVENT_ID:
        contract[name] = _extract_string_macro(event_id_text, name, EVENT_ID_H)
    for name in INT_MACROS_FROM_EVENT_ID:
        contract[name] = _extract_int_macro(event_id_text, name, EVENT_ID_H)

    lines = []
    lines.append("/*")
    lines.append(" * GENERATED by tools/gen_transport_contract_js.py from src/pipeline/transport_contract.h,")
    lines.append(" * src/pipeline/event_id.h, and src/pipeline/format_descriptor.json -- DO NOT EDIT.")
    lines.append(" * The reader page's (reader/, spec #115 sub-issue #119) own port of the SAME")
    lines.append(" * fragment/base32/URL/format-descriptor contract the cabinet-side C pipeline")
    lines.append(" * derives from (transport_contract.h's own header comment: the reader must")
    lines.append(" * independently port these values, since it is JavaScript, not a second")
    lines.append(" * includer of a C header -- this file is that port, generated, never")
    lines.append(" * hand-transcribed). Regenerate:")
    lines.append(" *   python3 tools/gen_transport_contract_js.py --out reader/generated/transport_contract.js")
    lines.append(" */")
    lines.append("")
    lines.append("export const TRANSPORT_CONTRACT = Object.freeze(%s);" %
                  json.dumps(contract, indent=2))
    # src/pipeline/format_descriptor.json's own human-facing "_comment" key
    # (~1.5 KB of prose) carries no information reader.js's unpackPayload()
    # needs -- it is metadata for a human reading the JSON source, not part
    # of the field-layout contract itself (gen_format_descriptor.py's own C
    # output already never reads it either). Strip every "_"-prefixed key
    # before embedding, so this file -- shipped to a phone over the
    # camera-triggered mobile connection that opened it -- carries only the
    # bytes the reader actually needs.
    format_descriptor_for_js = {k: v for k, v in format_descriptor.items() if not k.startswith("_")}

    lines.append("")
    lines.append("// src/pipeline/format_descriptor.json's field layout, embedded verbatim (single")
    lines.append("// JSON source shared with tools/gen_format_descriptor.py's C header -- see that")
    lines.append("// generator's own header comment for the field-offset-derivation rules")
    lines.append("// reader.js's unpackPayload() re-implements generically over this same field")
    lines.append("// list). \"_\"-prefixed human-facing keys (e.g. \"_comment\") are stripped: they")
    lines.append("// carry no wire-layout information and this file ships to a phone.")
    lines.append("export const FORMAT_DESCRIPTOR = Object.freeze(%s);" %
                  json.dumps(format_descriptor_for_js, indent=2))
    lines.append("")

    os.makedirs(os.path.dirname(os.path.abspath(args.out)), exist_ok=True)
    with open(args.out, "w") as f:
        f.write("\n".join(lines))


if __name__ == "__main__":
    sys.exit(main())
